name: Contract CI

on: push

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3

            - name: Install dependencies
              run: yarn install -D

            - name: Format Checker
              run: yarn fmtc
    build:
        runs-on: ubuntu-latest
        needs: lint

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3

            - name: Install dependencies
              run: yarn install -D

            - name: Compile Smart Contract
              run: yarn b
    test:
        runs-on: ubuntu-latest
        needs:
            - lint
            - build
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3

            - name: Install dependencies
              run: yarn install -D

            - name: Compile Smart Contract
              run: yarn b

            - name: Test Smart Contract
              run: yarn t
